# Generated by Django 4.2.11 on 2024-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='user', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default='password', max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[(0, '男性'), (1, '女性')], default='male', max_length=2)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
