# Generated by Django 4.2.11 on 2024-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='TSLA', max_length=100, verbose_name='公司名')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('adj_close', models.FloatField(verbose_name='调整后的收盘价')),
                ('volume', models.FloatField(verbose_name='成交量')),
            ],
            options={
                'verbose_name': '股票列表',
                'verbose_name_plural': '股票列表',
                'db_table': 'stock',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户列表', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@qq.com', max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('男', '男性'), ('女', '女性')], default='男', max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=100, verbose_name='密码'),
        ),
    ]
